"""
decompose/facets.py — Facet tagging module for sub-intents.

Assigns the correct facet key to each decomposed sub-intent candidate using
a dual strategy: fast keyword-based scoring with an optional embedding-based
fallback/refinement.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any, Optional

import yaml

try:
    from sentence_transformers import SentenceTransformer
    from sentence_transformers.util import cos_sim

    HAS_SENTENCE_TRANSFORMERS = True
except ImportError:
    HAS_SENTENCE_TRANSFORMERS = False


logger = logging.getLogger(__name__)


class FacetTagger:
    """Tags decomposed sub-intents with the most relevant facet key using embeddings."""

    def __init__(
        self,
        facets_config_path: str | Path,
        embedding_model_name: str = "BAAI/bge-small-en-v1.5",
        semantic_threshold: float = 0.5,
    ) -> None:
        """Initialize the FacetTagger.

        Args:
            facets_config_path: Path to the facets.yaml configuration.
            embedding_model_name: HuggingFace model name for sentence embeddings.
            semantic_threshold: Minimum cosine similarity required to assign a facet.
        """
        self.facets_config_path = Path(facets_config_path)
        self.semantic_threshold = semantic_threshold

        self.facets: dict[str, dict[str, Any]] = {}
        self.default_facet: str = "general"
        
        # Prefer .index/facets.yaml if available, since that's generated by Phase 0
        if self.facets_config_path.name == "facets.yaml" and self.facets_config_path.parent.name == "config":
            index_path = self.facets_config_path.parent.parent / ".index" / "facets.yaml"
            if index_path.exists():
                self.facets_config_path = index_path

        self._load_config()

        # Build embedding resources
        self.encoder: Optional[SentenceTransformer] = None
        self.facet_embeddings: Optional[Any] = None
        
        # Support both old config format (dict of dicts) and new format (list of dicts)
        if isinstance(self.facets, list):
            # New format from Phase 0
            self.facet_keys_ordered = [f["facet_id"] for f in self.facets]
            descriptions = [
                f"{f.get('display', f['facet_id'])}: {f.get('description', '')}"
                for f in self.facets
            ]
        else:
            # Old format
            self.facet_keys_ordered = list(self.facets.keys())
            descriptions = [
                f"{v.get('display', k)}: {v.get('description', '')}"
                for k, v in self.facets.items()
            ]

        if HAS_SENTENCE_TRANSFORMERS:
            try:
                logger.info(
                    f"Loading embedding model {embedding_model_name} for facet tagging."
                )
                self.encoder = SentenceTransformer(embedding_model_name)
                
                self.facet_embeddings = self.encoder.encode(
                    descriptions, convert_to_tensor=True
                )
                logger.info(
                    "Successfully loaded embedding model and pre-computed facet embeddings."
                )
            except Exception as e:
                logger.error(
                    f"Failed to load sentence-transformers model: {e}. "
                    "Facet tagging will always return default_facet."
                )
                self.encoder = None

    def _load_config(self) -> None:
        """Load facet definitions from the YAML config."""
        if not self.facets_config_path.exists():
            logger.error(f"Facets config not found at {self.facets_config_path}")
            raise FileNotFoundError(
                f"Config file not found: {self.facets_config_path}"
            )

        try:
            with open(self.facets_config_path, "r", encoding="utf-8") as f:
                config = yaml.safe_load(f)

            self.facets = config.get("facets", {})
            self.default_facet = config.get("default_facet", "general")
            # If loaded from Phase 0 generated yaml, default facet might not be explicitly defined at top level
            # It relies on the 'general' facet being in the list
            if isinstance(self.facets, list) and not config.get("default_facet"):
                self.default_facet = "general"

            if not self.facets:
                logger.warning("No facets defined in config.")

            logger.debug(f"Loaded {len(self.facets)} facets from config.")
        except Exception as e:
            logger.error(f"Failed to parse facets config: {e}")
            raise

    def tag(self, query_nl: str) -> str:
        """Assign the best matching facet key to a natural language query.

        Args:
            query_nl: The natural language sub-intent query.

        Returns:
            The best matching facet key, or the default facet if none match.
        """
        if not query_nl or not query_nl.strip():
            return self.default_facet

        # Embedding similarity
        if (
            self.encoder is not None
            and self.facet_embeddings is not None
            and len(self.facet_keys_ordered) > 0
        ):
            try:
                query_emb = self.encoder.encode(query_nl, convert_to_tensor=True)
                similarities = cos_sim(query_emb, self.facet_embeddings)[0]

                # Find the best match
                best_idx = similarities.argmax().item()
                best_score = similarities[best_idx].item()

                # Threshold for semantic match
                if best_score >= self.semantic_threshold:
                    best_facet = self.facet_keys_ordered[best_idx]
                    logger.debug(
                        f"Tagged '{query_nl}' as '{best_facet}' "
                        f"(embedding score: {best_score:.3f})"
                    )
                    return best_facet
            except Exception as e:
                logger.warning(
                    f"Embedding fallback failed for query '{query_nl}': {e}"
                )

        # Default
        logger.debug(f"Tagged '{query_nl}' as default facet '{self.default_facet}'")
        return self.default_facet

    def tag_batch(self, queries: list[str]) -> list[str]:
        """Tag a batch of sub-intents.

        Args:
            queries: A list of natural language queries.

        Returns:
            A list of facet keys corresponding to the queries.
        """
        if not queries:
            return []

        return [self.tag(q) for q in queries]
